apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  name: DEMO-greetings
  value: "Hello from the environment"

---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver
    image: nginx:latest
    ports:
    - containerPort: 80
    envFrom:
      - configMapRef:
          name: test-config
