apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
data:
  DB_user: YmFyMg==
  DB_password: bmF2ZWVu

---
apiVersion: v1
kind: Pod
metadata:
  name: web-secret
spec:
  containers:
  - name: web1
    image: nginx:latest
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
          name: secret-sa-sample

