apiVersion: v1
kind: Service
metadata:
  name: my-nodeport
spec:
  type: NodePort
  selector:
    app: webapps
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32000
---
apiVersion: v1
kind: Pod
metadata:
  name: test-nginx
  labels:
    app: webapps
spec:
  containers:
  - name: pod1
    image: nginx
    ports:
    - containerPort: 80
