apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: test-01
      image: nginx
      volumeMounts:
        - mountPath: "/sam/suman"
          name: mypvc
  volumes:
    - name: mypvc
      emptyDir: {}
