
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-app
  name: my-clusterip
spec:
  type: ClusterIp
  selector:
    app: nginx-app
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1    
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
